Models/Messenger/CreateGroupViewModel.cs
#region Library
using System.ComponentModel.DataAnnotations;
#endregion

namespace ChatWithSignal.Models.Messenger
{
    public class CreateGroupViewModel
    {
        [Required]
        [Display(Name = "Назва")]
        public string Name { get; set; }

        [Display(Name = "Публічна група")]
        public bool IsPublic { get; set; }
    }
}

Models/Messenger/GroupSettingsViewModel.cs
#region Library
using System;
using System.ComponentModel.DataAnnotations;
#endregion

namespace ChatWithSignal.Models.Messenger
{
    public class GroupSettingsViewModel
    {
        public Guid GroupId { get; set; }
        [Required]
        [Display(Name = "Назва")]
        public string Name { get; set; }

        [Display(Name = "Опис")]
        public string Text { get; set; }

        [Display(Name = "Публічна група")]
        public bool IsPublic { get; set; }
    }
}

Controllers/HomeController.cs
#region Library
using ChatWithSignal.Service.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
#endregion

namespace ChatWithSignal.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        #region Default
        private readonly IMessengerService _messengerService;

        public HomeController(IMessengerService messengerService)
        {
            _messengerService = messengerService;
        }
        #endregion

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var messengers = await _messengerService.GetMessengersAsync(User.Identity.Name);
            return View(messengers.OrderBy(x => x.LastDateTimeActive));
        }
    }
}

Controllers/IdentityController.cs
#region Library
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using ChatWithSignal.Models.Identity;
using ChatWithSignal.Domain.Identity;
#endregion

namespace ChatWithSignal.Controllers
{
    public class IdentityController : Controller
    {
        #region Default
        private readonly UserManager<Profile> _userManager;
        private readonly SignInManager<Profile> _singInManager;

        public IdentityController(UserManager<Profile> userManager, SignInManager<Profile> singInManager)
        {
            _userManager = userManager;
            _singInManager = singInManager;
        }
        #endregion

        #region View
        [AllowAnonymous]
        [HttpGet]
        public IActionResult Index()
            => View();
            
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await _singInManager.SignOutAsync();
            return RedirectToAction("Index", "Identity");
        }
        #endregion

        #region Processing
        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (!ModelState.IsValid)
                return View("Index");

            var profile = await _userManager.FindByEmailAsync(model.Email);

            if (profile != null)
            {
                await _singInManager.SignOutAsync();
                var result = await _singInManager.PasswordSignInAsync(profile, model.Password, model.RememberMe, false);

                if (result.Succeeded)
                    return RedirectToAction("Index", "Home");
                else
                    ModelState.AddModelError("", "Неправильна пошта або пароль");
            }
            else
                ModelState.AddModelError("", "Неправильна пошта або пароль");

            return View("Index");
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
                return View("Index");

            if (model.Password == model.RepeatPassword)
            {
                var IsExistProfile = await _userManager.FindByEmailAsync(model.Email);

                if (IsExistProfile == null)
                {
                    var profile = new Profile(model.NickName, model.Email);

                    await _userManager.CreateAsync(profile, model.Password);
                }

                return RedirectToAction("Index", "Identity");
            }
            else
                ModelState.AddModelError(nameof(RegisterViewModel.RepeatPassword), "Паролі не однакові");
            
            return View("Index");
        }
        #endregion
    }
}

Controllers/MessengerController.cs
#region Library
using ChatWithSignal.Models.Messenger;
using ChatWithSignal.Service.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
#endregion

namespace ChatWithSignal.Controllers
{
    [Authorize]
    public class MessengerController : Controller
    {
        #region Default
        private readonly IMessengerService _messengerService;

        public MessengerController(IMessengerService messengerService)
        {
            _messengerService = messengerService;
        }
        #endregion

        #region View
        [HttpGet]
        public async Task<IActionResult> OpenChat(string profileId)
        {
            await _messengerService.GetOrCreateChatAsync(User.Identity.Name, profileId);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> JoinGroup(Guid messengerId)
        {
            await _messengerService.GetOrJoinGroupAsync(User.Identity.Name, messengerId);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult CreateGroup() 
            => View(new CreateGroupViewModel());

        [HttpGet]
        public async Task<IActionResult> GroupSettings(Guid groupId)
        {
            var group = await _messengerService.GetOrJoinGroupAsync(User.Identity.Name, groupId);

            if (group != null)
                return View(new GroupSettingsViewModel { GroupId = group.Id, Text = group.Text, IsPublic = group.IsPublic, Name = group.Name });

            return RedirectToAction("Index", "Home");
        }
        #endregion

        #region Processing
        [HttpPost]
        public async Task<IActionResult> CreateGroup(CreateGroupViewModel model)
        {
            if (ModelState.IsValid)
                await _messengerService.CreateGroupAsync(User.Identity.Name, model.Name, model.IsPublic);

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> GroupSettings(GroupSettingsViewModel model)
        {
            await _messengerService.ChangeGroupSettingsAsync(User.Identity.Name, model);

            return RedirectToAction("Index", "Home");
        }
        #endregion
    }
}

Controllers/SearchController.cs
#region Library
using ChatWithSignal.Domain.Search;
using ChatWithSignal.Service.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
#endregion

namespace ChatWithSignal.Controllers
{
    [Authorize]
    public class SearchController : Controller
    {
        #region Default
        private readonly IMessengerService _messengerService;
        private readonly IProfileService _profileService;

        public SearchController(IMessengerService messengerService, IProfileService profileService)
        {
            _messengerService = messengerService;
            _profileService = profileService;
        }
        #endregion

        #region View
        [HttpGet]
        public IActionResult Index() 
            => RedirectToAction("Profiles", "Search");
        
        [HttpGet]
        public async Task<IActionResult> Profiles()
        {
            var profiles = await _profileService.GetSAsync();
            var activeProfile = await _profileService.GetByEmailAsync(User.Identity.Name);

            profiles.Remove(profiles.First(x => x.Id == activeProfile.Id));

            return View(profiles);
        }

        [HttpGet]
        public async Task<IActionResult> Groups() 
            => View(await _messengerService.GetSearchGroupsAsync());
        #endregion
    }
}

Views/Home/Index.cshtml
@{
IEnumerable<Messenger> messengers = Model;
}

<link rel="stylesheet" href="~/css/Home/Main.css" />
<link rel="stylesheet" href="~/css/Home/MessengersZone.css" />
<link rel="stylesheet" href="~/css/Home/OpenMessengers.css" />
<div class="messengers-area">
    <div class="messenger-box" id="messengers-zone">
        <div class="create-group">
            <a class="button-type" method="post" asp-controller="Messenger" asp-action="CreateGroup">Створити групу</a>
        </div>

        <div class="messengers-list" id="messengers">
        </div>
    </div>

    <div class="messenger-box" id="open-messenger">
        <div id="chatroom"></div>

        <div id="inputForm">
            <input type="text" id="message" />
            <input type="button" id="sendContent" value="Відправити" />
        </div>
    </div>
</div>


<script type="text/javascript">
    let messengersData = @Html.Raw(JsonConvert.SerializeObject(Model));
</script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="~/js/homeIndex.js"></script>
<script src="~/js/signalr/dist/browser/signalr.min.js"></script>
<script src="~/js/signalr/config.js"></script>

Views/Messenger/CreateGroup.cshtml
@model CreateGroupViewModel
<h2>Створення Групи</h2>

<div class="group-box">
    <form asp-controller="Messenger" asp-action="CreateGroup" method="post">

        <div class="string-parametrs" id="name">
            <label asp-for="Name"></label>
            <br />
            <input asp-for="Name" />
        </div>

        <div class="checkbox" id="ispublic">
            <label asp-for="IsPublic"></label>
            <input asp-for="IsPublic" type="checkbox" />
        </div>
        
        <div class="action-buttons">
            <input type="submit" asp-controller="Messenger" asp-action="CreateGroup" value="Створити" />
        </div>

    </form>
</div>

Views/Messenger/GroupSettings.cshtml
@model GroupSettingsViewModel

<div class="group-box">
    <form asp-controller="Messenger" asp-action="GroupSettings" method="post">

        <input asp-for="GroupId" type="hidden" value="@Model.GroupId" />

        <div class="string-parametrs" id="name">
            <input asp-for="Name" value="@Model.Name" />
            <span asp-validation-for="Name" />
        </div>

        <div class="string-parametrs" id="text">
            <input asp-for="Text" value="@Model.Text" />
            <span asp-validation-for="Text" />
        </div>

        <div class="checkbox" id="ispublic">
            <input asp-for="IsPublic" value="@Model.IsPublic" />
            <span asp-validation-for="IsPublic" />
        </div>

        <div class="action-buttons">
            <input type="submit" asp-controller="Messenger" asp-action="GroupSettings" value="Зберегти" />
        </div>

    </form>
</div>

Views/Search/Filter.cshtml
<div>
    <h4>Пошук:
        <a method="post" asp-controller="Search" asp-action="Profiles">Профілі</a>
        <a method="post" asp-controller="Search" asp-action="Groups">Групи</a>
    </h4>
</div>

Views/Search/Groups.cshtml
@{
    ViewBag.Title = "Пошук";
    ICollection<BaseMessenger> groups = Model;
}

<div class="search-components">
    <h3>Список груп</h3>
    <br />

    @await Html.PartialAsync("Filter")
</div>

<div class="search-list">
    @foreach (var group in groups)
    {
        <h5>
            @group.Name - <a asp-controller="Messenger" asp-action="JoinGroup" method="post" asp-route-messengerId="@group.Id">Приєднатися</a>
        </h5>
    }
</div>

Views/Search/Profiles.cshtml
@{
    ViewBag.Title = "Пошук";
    ICollection<SearchProfile> profiles = Model;
}
<div class="search-components">
    <h3>Список профілів</h3>
    <br />

    @await Html.PartialAsync("Filter")
</div>

<div class="search-list">
    @foreach (var profile in profiles)
    {
        <h5>
            @profile.NickName - <a asp-controller="Messenger" asp-action="OpenChat" method="get" asp-route-profileId="@profile.Id">Написати</a>
        </h5>
        <br />
    }
</div>

Views/Shared/FooterPartial.cshtml
<footer class="footer">
    <h6>&copy; 2023 - @Config.Name</h6>
</footer>

Views/Shared/HeadPartial.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/Shared/Header.css" />
<link rel="stylesheet" href="~/css/Shared/Main.css" />
<title>@Config.Name</title>

Views/Shared/HeaderPartial.cshtml
@if(User.Identity.IsAuthenticated)
{
    <header class="header">
        <nav id="nav">
            <ul>
                <li>
                    <a asp-controller="Home" asp-action="Index">Головна</a>
                </li>
                <li>
                    <a asp-controller="Search" asp-action="Index">Пошук</a>
                </li>
            </ul>
        </nav>
    </header>
}

Views/Shared/ScriptPartial.cshtml
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @await Html.PartialAsync("HeadPartial")
</head>
<body>
    @await Html.PartialAsync("ScriptPartial")
    @await Html.PartialAsync("HeaderPartial")

    <div class="main-container">
        <main role="main" class="main">
            @RenderBody()
        </main>
    </div>

    @await Html.PartialAsync("FooterPartial")
</body>
</html>